// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	int number = Integer.parseInt(args[0]);
	int greaterthan = 0;
	int lessthan = 0;
	for(int i =0;i<number;i++)
	{
		double random = Math.random();
		if(random>0.5)greaterthan+=1;
		else lessthan+=1;
	}
	System.out.println("> 0.5:  " +greaterthan + " times");
	System.out.println("<= 0.5:  " +lessthan + " times");
	double Ratio = (double)greaterthan/(double)lessthan;
	if(!Double.isInfinite(Ratio)){System.out.println("Ratio:  " + Ratio);};





}
}
